# Generated by Django 5.0.2 on 2024-03-07 14:42

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterforLocation',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='location_media/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('web', models.URLField(unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('open_hours', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations_filtered', to='orgs.filterforlocation', verbose_name='filter')),
                ('related_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='orgs.organisation')),
            ],
        ),
    ]
