# Generated by Django 5.0.2 on 2024-04-06 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_organisation_orgs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='orgs',
        ),
        migrations.AddField(
            model_name='organisation',
            name='agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
