# Generated by Django 5.0.2 on 2024-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-profile'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
