# Generated by Django 5.0.2 on 2024-04-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_locationmedia_options_alter_locations_options_and_more'),
        ('users', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_org_agent',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orgs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='orgs.organisation'),
        ),
    ]
