# Generated by Django 5.0.2 on 2024-04-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_org_agent_userprofile_orgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='orgs',
        ),
    ]
