# Generated by Django 5.0.2 on 2024-04-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmed_user',
            field=models.BooleanField(default=True, verbose_name='confirmed user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document_file',
            field=models.FileField(default=True, upload_to='media/users_documents', verbose_name='PDF document'),
            preserve_default=False,
        ),
    ]
