# Generated by Django 5.0.2 on 2024-05-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_confirmed_user_userprofile_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmed_user',
            field=models.BooleanField(default=False, verbose_name='confirmed user'),
        ),
    ]
