# Generated by Django 5.0.2 on 2024-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_confirmed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirmed_user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_org_agent',
            field=models.CharField(choices=[('None', 'None'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='none', max_length=20, verbose_name='confirmed user'),
        ),
    ]
